const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    LOGOUT: "/auth/logout",
    PROFILE: "/users/get",
  },
  USER: {
    GET_PROFILE: "/users/get",
    UPDATE_PROFILE: "/users/update",
    GET_ALL: "/users/getAll",
    DELETE: "/users/delete?userId=",
  },
  DASHBOARD: {
    GET_DASHBOARD: "/dashboard/stats",
    GET_FINANCIALS: "/dashboard/financials",
    GET_FINANCIAL_TRANSACTIONS: "/dashboard/financials/transactions",
    GET_FINANCIAL_USERS: "/dashboard/financials/users",
    GET_FINANCIAL_SESSIONS: "/dashboard/financials/sessions",
  },
  CATEGORIES: {
    CREATE: "/categories/create",
    UPDATE: "/categories/update/:id",
    DELETE: "/categories/delete/",
    GET_ALL: "/categories/getAll",
    GET_ONE: "/categories/get/:id",
  },
  COMMUNITIES: {
    CREATE: "/communities/create",
    UPDATE: "/communities/update/:id",
    DELETE: "/communities/delete/",
    GET_ALL: "/communities/admin/getAll",
    GET_ONE: "/communities/admin/get/:id",
    GET_PRICING: "/communities/admin/pricing",
    UPDATE_PRICING: "/communities/admin/pricing",
  },
  THERAPY: {
    CREATE: "/therapy/admin/create",
    UPDATE: "/therapy/admin/update/:id",
    DELETE: "/therapy/admin/delete/",
    GET_ALL: "/therapy/admin/getAll",
    GET_ONE: "/therapy/admin/get/:id",
  },
  CAREERS: {
    CREATE: "/careers/create",
    UPDATE: "/careers/update/:id",
    DELETE: "/careers/delete/",
    GET_ALL: "/careers/admin/getAll",
    GET_ONE: "/careers/admin/get/:id",
    APPLICATIONS: "/careers/admin/applications",
    UPDATE_APPLICATION_STATUS: "/careers/admin/applications/",
  },
  MENTORS: {
    CREATE: "/mentors/create",
    GET_ALL: "/mentors/getAll",
    GET_ONE: "/mentors/get",
    UPDATE: "/mentors/update",
    RESET_PASSWORD: "/mentors/reset-password",
    DELETE: "/users/delete?userId=",
  },
  MATES: {
    CREATE: "/mates/create",
    GET_ALL: "/mates/getAll",
    GET_ONE: "/mates/get/:id",
    UPDATE: "/mates/update/:id",
    DELETE: "/users/delete?userId=",
  },
  MENTEES: {
    CREATE: "/mentees/create",
    GET_ALL: "/mentees/getAll",
    GET_ONE: "/mentees/get/:id",
    UPDATE: "/mentees/update/:id",
    DELETE: "/mentees/delete/:id",
  },
  SMS: {
    BULK: "/sms/bulk",
  },
  MATE_AVAILABILITY: {
    OVERVIEW: "/mate-availability/tracking/overview",
    ONLINE: "/mate-availability/tracking/online",
    ACTIVITY: "/mate-availability/tracking/activity",
    SUMMARY: "/mate-availability/tracking/summary",
    DAILY_STATS: "/mate-availability/tracking",
  },
  MODERATION: {
    BLOCKED_IPS: "/moderation/blocked-ips",
    UNBLOCK_IP: "/moderation/unblock-ip",
    BLOCK_IP: "/moderation/block-ip",
  },
};

export default API_ENDPOINTS;
